import { metadata } from '../layout'

describe('RootLayout', () => {
  it('exports metadata with correct title', () => {
    expect(metadata?.title).toBe('Create Next App')
  })

  it('exports metadata with correct description', () => {
    expect(metadata?.description).toBe('Generated by create next app')
  })

  it('exports correct metadata structure', () => {
    expect(metadata).toEqual({
      title: 'Create Next App',
      description: 'Generated by create next app',
    })
  })
})
